version: '3.5'
services:
  python3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'python3'
    working_dir: '/usr/html'
    tty: true
    volumes:
      - ./html:/usr/html
